apiVersion: v1
kind: Service
metadata:  
  name: pgadmin-svc
spec:
  selector:    
    app: {{ .Values.pgadmin.label }}
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP